name: Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    uses: jw-project/workflows/.github/workflows/publish-mfe.yml@main
    secrets:
      package_token: ${{ secrets.PACKAGE_TOKEN }}
      supabase_auth: ${{ secrets.SUPABASE_AUTH }}
