name: Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  publish:
    uses: jw-project/workflows/.github/workflows/publish-mfe.yml@main
    secrets:
      package_token: ${{ secrets.PACKAGE_TOKEN }}
      firebase_auth: ${{ secrets.FIREBASE_AUTH }}
      firebase_token: ${{ secrets.FIREBASE_TOKEN }}
      firebase_project: ${{ secrets.FIREBASE_PROJECT_PROD }}
